#:import menu menu

MainWidget:
#:set s dp(150)

<MainWidget>:
    MenuWidget:
    Label: 
        text: root.score_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf'
        size_hint: .2, .2
        pos_hint: {"x":0, "top":1}
    
    Label: 
        text: root.health_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf'
        size_hint: .2, .2
        pos_hint: {"x":0.7, "top":1}
    
    

